# -*- coding: utf-8 -*-
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment

# Each row: (English, Vietnamese, Pronunciation, Filename)
# Where the same filename = same recording (shared between cheatsheet & quiz)

tabs = {
    "Tones & Alphabet": [
        ("flat tone", "ngang", "ngang", "tone_ngang.mp3"),
        ("falling tone", "huyền", "hwee-en", "tone_huyen.mp3"),
        ("rising tone", "sắc", "sak", "tone_sac.mp3"),
        ("questioning tone", "hỏi", "hoy", "tone_hoi.mp3"),
        ("broken tone", "ngã", "nga", "tone_nga.mp3"),
        ("heavy tone", "nặng", "nuhng", "tone_nang.mp3"),
        ("ghost (flat tone example)", "ma", "mah", "word_ma.mp3"),
        ("but / however (falling tone)", "mà", "mah (falling)", "word_ma_huyen.mp3"),
        ("cheek / mum - Southern (rising tone)", "má", "mah (rising)", "word_ma_sac.mp3"),
        ("tomb / grave (questioning tone)", "mả", "mah (dip-rise)", "word_ma_hoi.mp3"),
        ("horse / code (broken tone)", "mã", "mah (break)", "word_ma_nga.mp3"),
        ("rice seedling (heavy tone)", "mạ", "mah (heavy-stop)", "word_ma_nang.mp3"),
        ("friend / you (heavy dot tone)", "bạn", "bahn (heavy)", "word_ban.mp3"),
        ("to sell (rising tone)", "bán", "bahn (rising)", "word_ban_sac.mp3"),
        ("table / to discuss (falling tone)", "bàn", "bahn (falling)", "word_ban_huyen.mp3"),
        ("no / not / zero (flat tone)", "không", "khome (flat)", "num_0.mp3"),
        ("huge (questioning tone)", "khổng", "khome (questioning)", "word_khong_hoi.mp3"),
        ("thank you", "cảm ơn", "kahm uhn", "phrase_thank_you.mp3"),
        ("delicious (flat tone example)", "ngon", "ngawn (flat)", "word_ngon.mp3"),
        ("tip / flame (heavy tone example)", "ngọn", "ngawn (heavy)", "word_ngon_nang.mp3"),
    ],
    "Numbers": [
        ("zero / no / not", "không", "khome", "num_0.mp3"),
        ("one", "một", "moht", "num_1.mp3"),
        ("two", "hai", "hi", "num_2.mp3"),
        ("three", "ba", "bah", "num_3.mp3"),
        ("four", "bốn", "bone", "num_4.mp3"),
        ("five / year", "năm", "num", "num_5.mp3"),
        ("six", "sáu", "sow", "num_6.mp3"),
        ("seven", "bảy", "bay", "num_7.mp3"),
        ("eight", "tám", "tahm", "num_8.mp3"),
        ("nine", "chín", "chin", "num_9.mp3"),
        ("ten", "mười", "muh-ee", "num_10.mp3"),
        ("eleven", "mười một", "muh-ee moht", "num_11.mp3"),
        ("twelve", "mười hai", "muh-ee hi", "num_12.mp3"),
        ("thirteen", "mười ba", "muh-ee bah", "num_13.mp3"),
        ("fourteen", "mười bốn", "muh-ee bone", "num_14.mp3"),
        ("fifteen", "mười lăm", "muh-ee lum", "num_15.mp3"),
        ("sixteen", "mười sáu", "muh-ee sow", "num_16.mp3"),
        ("seventeen", "mười bảy", "muh-ee bay", "num_17.mp3"),
        ("eighteen", "mười tám", "muh-ee tahm", "num_18.mp3"),
        ("nineteen", "mười chín", "muh-ee chin", "num_19.mp3"),
        ("twenty", "hai mươi", "hi muh-ee", "num_20.mp3"),
        ("twenty-one", "hai mươi mốt", "hi muh-ee moht", "num_21.mp3"),
        ("twenty-five", "hai mươi lăm", "hi muh-ee lum", "num_25.mp3"),
        ("thirty", "ba mươi", "bah muh-ee", "num_30.mp3"),
        ("forty", "bốn mươi", "bone muh-ee", "num_40.mp3"),
        ("fifty", "năm mươi", "num muh-ee", "num_50.mp3"),
        ("sixty", "sáu mươi", "sow muh-ee", "num_60.mp3"),
        ("seventy", "bảy mươi", "bay muh-ee", "num_70.mp3"),
        ("eighty", "tám mươi", "tahm muh-ee", "num_80.mp3"),
        ("ninety", "chín mươi", "chin muh-ee", "num_90.mp3"),
        ("one hundred", "một trăm", "moht chum", "num_100.mp3"),
        ("two hundred", "hai trăm", "hi chum", "num_200.mp3"),
        ("five hundred", "năm trăm", "num chum", "num_500.mp3"),
        ("one thousand", "một nghìn", "moht ngin", "num_1000.mp3"),
        ("ten thousand", "mười nghìn", "muh-ee ngin", "num_10000.mp3"),
        ("one hundred thousand", "một trăm nghìn", "moht chum ngin", "num_100000.mp3"),
        ("one million", "một triệu", "moht chyew", "num_1000000.mp3"),
        ("hundred", "trăm", "chum", "num_tram.mp3"),
        ("thousand", "nghìn / ngàn", "ngin / ngahn", "num_nghin.mp3"),
        ("million", "triệu", "chyew", "num_trieu.mp3"),
        ("o'clock / hour", "giờ", "yuh", "time_oclock.mp3"),
        ("morning", "sáng", "sahng", "time_morning.mp3"),
        ("midday / noon", "trưa", "chuh-ah", "time_noon.mp3"),
        ("afternoon", "chiều", "chyew", "time_afternoon.mp3"),
        ("evening", "tối", "toy", "time_evening.mp3"),
        ("night", "đêm", "dem", "time_night.mp3"),
        ("half past", "rưỡi", "ruh-ee", "time_half.mp3"),
        ("day", "ngày", "nay", "time_day.mp3"),
        ("month", "tháng", "tung", "time_month.mp3"),
        ("dong (currency)", "đồng", "dome", "money_dong.mp3"),
    ],
    "Greetings & Phrases": [
        ("hello", "Xin chào", "sin chow", "greet_hello.mp3"),
        ("goodbye", "Tạm biệt", "tahm byet", "greet_goodbye.mp3"),
        ("see you again", "Hẹn gặp lại", "hen gup lie", "greet_see_you.mp3"),
        ("good morning", "Chào buổi sáng", "chow boo-oy sahng", "greet_good_morning.mp3"),
        ("good afternoon", "Chào buổi chiều", "chow boo-oy chyew", "greet_good_afternoon.mp3"),
        ("good evening", "Chào buổi tối", "chow boo-oy toy", "greet_good_evening.mp3"),
        ("good night", "Chúc ngủ ngon", "chook ngoo ngawn", "greet_good_night.mp3"),
        ("what is your name?", "Bạn tên gì?", "bahn ten yee", "phrase_your_name.mp3"),
        ("my name is...", "Tên tôi là...", "ten toy lah", "phrase_my_name.mp3"),
        ("nice to meet you", "Rất vui được gặp bạn", "rut voo-ee duh-uk gup bahn", "phrase_nice_to_meet.mp3"),
        ("how are you?", "Bạn khỏe không?", "bahn khway khome", "phrase_how_are_you.mp3"),
        ("I'm fine", "Tôi khỏe", "toy khway", "phrase_im_fine.mp3"),
        ("and you?", "Còn bạn?", "kawn bahn", "phrase_and_you.mp3"),
        ("where are you from?", "Bạn từ đâu đến?", "bahn tuh doh den", "phrase_where_from.mp3"),
        ("I'm from America", "Tôi từ Mỹ đến", "toy tuh mee den", "phrase_from_america.mp3"),
        ("thank you", "Cảm ơn", "cahm uhn", "phrase_thank_you.mp3"),
        ("thank you very much", "Cảm ơn nhiều", "cahm uhn nyew", "phrase_thank_you_much.mp3"),
        ("you're welcome", "Không có gì", "khome kaw yee", "phrase_youre_welcome.mp3"),
        ("sorry / excuse me", "Xin lỗi", "sin loy", "phrase_sorry.mp3"),
        ("please", "Làm ơn", "lahm uhn", "phrase_please.mp3"),
        ("yes (polite, Southern)", "Dạ", "yah", "phrase_yes_polite.mp3"),
        ("yes (polite, Northern)", "Vâng", "vung", "phrase_yes_northern.mp3"),
        ("yes (casual)", "Ừ", "uh", "phrase_yes_casual.mp3"),
        ("no / not / zero", "Không", "khome", "num_0.mp3"),
        ("no thank you", "Không, cảm ơn", "khome, cahm uhn", "phrase_no_thank_you.mp3"),
        ("OK / alright", "Được", "duh-uk", "phrase_ok.mp3"),
        ("no problem", "Không sao", "khome sow", "phrase_no_problem.mp3"),
        ("really?", "Thật không?", "thut khome", "phrase_really.mp3"),
        ("I know", "Tôi biết", "toy byet", "phrase_i_know.mp3"),
        ("I don't know", "Tôi không biết", "toy khome byet", "phrase_i_dont_know.mp3"),
        ("maybe", "Có thể", "kaw theh", "phrase_maybe.mp3"),
        ("of course", "Tất nhiên", "tut nyen", "phrase_of_course.mp3"),
        ("same same", "Như nhau", "nyuh nyow", "phrase_same_same.mp3"),
        ("I don't understand", "Tôi không hiểu", "toy khome hyew", "phrase_dont_understand.mp3"),
        ("I don't speak Vietnamese well", "Tôi nói tiếng Việt không giỏi", "toy noy tyeng vyet khome yoy", "phrase_no_vietnamese.mp3"),
        ("please say that again", "Nói lại đi", "noy lie dee", "phrase_say_again.mp3"),
        ("please speak more slowly", "Nói chậm hơn", "noy chum huhn", "phrase_speak_slowly.mp3"),
        ("do you speak English?", "Bạn nói tiếng Anh không?", "bahn noy tyeng anh khome", "phrase_speak_english.mp3"),
        ("can you help me?", "Bạn có thể giúp tôi không?", "bahn kaw theh yoop toy khome", "phrase_help_me.mp3"),
        ("I need help", "Tôi cần giúp đỡ", "toy kun yoop duh", "phrase_need_help.mp3"),
        ("I'm lost", "Tôi bị lạc", "toy bee lahk", "phrase_im_lost.mp3"),
        ("where is...?", "...ở đâu?", "uh doh", "dir_where_is.mp3"),
        ("turn left", "Rẽ trái", "reh chai", "dir_left.mp3"),
        ("turn right", "Rẽ phải", "reh fai", "dir_right.mp3"),
        ("go straight", "Đi thẳng", "dee tung", "dir_straight.mp3"),
        ("turn around / go back", "Quay lại", "kway lie", "dir_turn_around.mp3"),
        ("near", "Gần", "gun", "dir_near.mp3"),
        ("far", "Xa", "sah", "dir_far.mp3"),
        ("how far?", "Bao xa?", "bow sah", "dir_how_far.mp3"),
        ("how long? (time)", "Bao lâu?", "bow loh", "dir_how_long.mp3"),
        ("stop here", "Dừng ở đây", "yung uh day", "dir_stop_here.mp3"),
        ("I / me (neutral)", "tôi", "toy", "pron_i.mp3"),
        ("you (friend, your age)", "bạn", "bahn", "pron_you_friend.mp3"),
        ("you (older male) / I (speaking to older female)", "anh", "anh", "pron_anh.mp3"),
        ("you (older female) / I (speaking to older male)", "chị", "chee", "pron_chi.mp3"),
        ("I / you (younger person)", "em", "em", "pron_em.mp3"),
        ("you (uncle-aged male)", "chú", "choo", "pron_chu.mp3"),
        ("you (aunt-aged female)", "cô", "koh", "pron_co.mp3"),
        ("you (grandfather-aged)", "ông", "ome", "pron_ong.mp3"),
        ("you (grandmother-aged)", "bà", "bah", "pron_ba.mp3"),
    ],
    "Food & Drinks": [
        ("pho (rice noodle soup)", "phở", "fuh", "food_pho.mp3"),
        ("beef pho", "phở bò", "fuh baw", "food_pho_beef.mp3"),
        ("chicken pho", "phở gà", "fuh gah", "food_pho_chicken.mp3"),
        ("banh mi", "bánh mì", "bahn mee", "food_banh_mi.mp3"),
        ("fresh spring rolls", "gỏi cuốn", "goy koo-uhn", "food_goi_cuon.mp3"),
        ("fried spring rolls", "chả giò", "chah yaw", "food_cha_gio.mp3"),
        ("broken rice", "cơm tấm", "kum tum", "food_com_tam.mp3"),
        ("sizzling crepe", "bánh xèo", "bahn say-oh", "food_banh_xeo.mp3"),
        ("Hue beef noodles", "bún bò Huế", "boon baw hweh", "food_bun_bo_hue.mp3"),
        ("grilled pork noodles", "bún thịt nướng", "boon tit nyuh-ung", "food_bun_thit_nuong.mp3"),
        ("Hanoi grilled pork", "bún chả", "boon chah", "food_bun_cha.mp3"),
        ("steamed rice rolls", "bánh cuốn", "bahn koo-uhn", "food_banh_cuon.mp3"),
        ("Hoi An noodles", "cao lầu", "kow loh", "food_cao_lau.mp3"),
        ("southern noodle soup", "hủ tiếu", "hoo tyew", "food_hu_tieu.mp3"),
        ("I want to order", "Tôi muốn gọi món", "toy moo-uhn goy mawn", "order_want_to_order.mp3"),
        ("give me one of these", "Cho tôi một cái này", "chaw toy moht kai nay", "order_one_of_these.mp3"),
        ("one bowl", "Một tô", "moht toh", "order_one_bowl.mp3"),
        ("two bowls", "Hai tô", "hi toh", "order_two_bowls.mp3"),
        ("the bill please", "Tính tiền đi", "ting tyen dee", "order_bill.mp3"),
        ("delicious!", "Ngon lắm!", "ngawn lahm", "order_delicious.mp3"),
        ("too spicy", "Cay quá", "kay kwah", "order_too_spicy.mp3"),
        ("not spicy", "Không cay", "khome kay", "order_not_spicy.mp3"),
        ("a little spicy", "Ít cay", "it kay", "order_little_spicy.mp3"),
        ("very spicy", "Cay nhiều", "kay nyew", "order_very_spicy.mp3"),
        ("no ice", "Không đá", "khome dah", "order_no_ice.mp3"),
        ("less ice", "Ít đá", "it dah", "order_less_ice.mp3"),
        ("no sugar", "Không đường", "khome duh-ung", "order_no_sugar.mp3"),
        ("more please", "Thêm nữa đi", "tem nyuh dee", "order_more.mp3"),
        ("what is this?", "Cái này là gì?", "kai nay lah yee", "order_what_is_this.mp3"),
        ("vegetarian", "Ăn chay", "un chay", "order_vegetarian.mp3"),
        ("no meat", "Không thịt", "khome tit", "order_no_meat.mp3"),
        ("extra broth", "Thêm nước lèo", "tem nyuhk lay-oh", "order_extra_broth.mp3"),
        ("extra noodles", "Thêm bún", "tem boon", "order_extra_noodles.mp3"),
        ("extra meat", "Thêm thịt", "tem tit", "order_extra_meat.mp3"),
        ("well done beef", "Bò chín", "baw chin", "order_beef_well_done.mp3"),
        ("rare beef", "Bò tái", "baw tie", "order_beef_rare.mp3"),
        ("beef", "bò", "baw", "food_beef.mp3"),
        ("chicken", "gà", "gah", "food_chicken.mp3"),
        ("pork", "heo / lợn", "hey-oh / luhn", "food_pork.mp3"),
        ("duck", "vịt", "vit", "food_duck.mp3"),
        ("shrimp", "tôm", "tome", "food_shrimp.mp3"),
        ("fish", "cá", "kah", "food_fish.mp3"),
        ("squid", "mực", "muk", "food_squid.mp3"),
        ("crab", "cua", "koo-ah", "food_crab.mp3"),
        ("tofu", "đậu hũ", "doh hoo", "food_tofu.mp3"),
        ("fish sauce", "nước mắm", "nyuhk mum", "food_fish_sauce.mp3"),
        ("chili sauce", "tương ớt", "tuh-ung uht", "food_chili_sauce.mp3"),
        ("hoisin sauce", "tương hoisin", "tuh-ung hoy-sin", "food_hoisin.mp3"),
        ("fresh chili", "ớt tươi", "uht tuh-ee", "food_fresh_chili.mp3"),
        ("fresh lime", "chanh tươi", "chan tuh-ee", "food_lime.mp3"),
        ("bean sprouts", "giá", "yah", "food_bean_sprouts.mp3"),
        ("Vietnamese mint / herbs", "rau thơm", "row thum", "food_herbs.mp3"),
        ("basil", "húng quế", "hoong kweh", "food_basil.mp3"),
        ("iced coffee with milk", "cà phê sữa đá", "kah feh shuh-ah dah", "drink_ca_phe_sua_da.mp3"),
        ("hot coffee with milk", "cà phê sữa nóng", "kah feh shuh-ah nawng", "drink_ca_phe_sua_nong.mp3"),
        ("iced black coffee", "cà phê đen đá", "kah feh den dah", "drink_ca_phe_den_da.mp3"),
        ("drip filter coffee", "cà phê phin", "kah feh fin", "drink_ca_phe_phin.mp3"),
        ("egg coffee", "cà phê trứng", "kah feh chung", "drink_ca_phe_trung.mp3"),
        ("coconut coffee", "cà phê cốt dừa", "kah feh koht yuh-ah", "drink_ca_phe_dua.mp3"),
        ("Saigon-style light coffee", "bạc xỉu", "bahk syew", "drink_bac_xiu.mp3"),
        ("salt coffee", "cà phê muối", "kah feh moo-oy", "drink_ca_phe_muoi.mp3"),
        ("iced tea (usually free)", "trà đá", "chah dah", "drink_tra_da.mp3"),
        ("hot tea", "trà nóng", "chah nawng", "drink_tra_nong.mp3"),
        ("milk tea / bubble tea", "trà sữa", "chah shuh-ah", "drink_tra_sua.mp3"),
        ("fresh fruit smoothie", "sinh tố", "sing toh", "drink_sinh_to.mp3"),
        ("fresh fruit juice", "nước ép", "nyuhk ep", "drink_nuoc_ep.mp3"),
        ("coconut water", "nước dừa", "nyuhk yuh-ah", "drink_nuoc_dua.mp3"),
        ("sugarcane juice", "nước mía", "nyuhk myah", "drink_nuoc_mia.mp3"),
        ("still water", "nước lọc", "nyuhk lawk", "drink_nuoc_loc.mp3"),
        ("beer", "bia", "byah", "drink_beer.mp3"),
    ],
    "Colors & Descriptions": [
        ("red", "đỏ", "daw", "color_red.mp3"),
        ("blue", "xanh dương", "sahn yuh-ung", "color_blue.mp3"),
        ("green", "xanh lá", "sahn lah", "color_green.mp3"),
        ("yellow", "vàng", "vahng", "color_yellow.mp3"),
        ("white", "trắng", "chung", "color_white.mp3"),
        ("black", "đen", "den", "color_black.mp3"),
        ("orange", "cam", "kahm", "color_orange.mp3"),
        ("pink", "hồng", "hohng", "color_pink.mp3"),
        ("purple", "tím", "tim", "color_purple.mp3"),
        ("brown", "nâu", "noh", "color_brown.mp3"),
        ("grey", "xám", "sahm", "color_grey.mp3"),
        ("dark (deep shade)", "đậm", "dum", "color_dark.mp3"),
        ("light (pale shade)", "nhạt", "nyat", "color_light.mp3"),
        ("color", "màu", "mow", "desc_color.mp3"),
        ("big / large", "to / lớn", "taw / luhn", "size_big.mp3"),
        ("small / little", "nhỏ / bé", "nyaw / beh", "size_small.mp3"),
        ("medium / just right", "vừa", "vyuh-ah", "size_medium.mp3"),
        ("long", "dài", "die", "size_long.mp3"),
        ("short (length)", "ngắn", "ngun", "size_short_length.mp3"),
        ("wide / broad", "rộng", "rawng", "size_wide.mp3"),
        ("narrow", "hẹp", "hep", "size_narrow.mp3"),
        ("thick", "dày", "day", "size_thick.mp3"),
        ("thin", "mỏng", "mawng", "size_thin.mp3"),
        ("tall (height)", "cao", "kow", "size_tall.mp3"),
        ("short (height)", "thấp", "tup", "size_short_height.mp3"),
        ("heavy", "nặng", "nung", "size_heavy.mp3"),
        ("light (weight)", "nhẹ", "nyeh", "size_light.mp3"),
        ("beautiful / pretty", "đẹp", "dep", "adj_beautiful.mp3"),
        ("ugly", "xấu", "soh", "adj_ugly.mp3"),
        ("good", "tốt", "tote", "adj_good.mp3"),
        ("bad", "tệ", "teh", "adj_bad.mp3"),
        ("new", "mới", "muh-ee", "adj_new.mp3"),
        ("old / used", "cũ", "koo", "adj_old.mp3"),
        ("expensive", "đắt", "dat", "adj_expensive.mp3"),
        ("cheap", "rẻ", "reh", "adj_cheap.mp3"),
        ("hot", "nóng", "nawng", "adj_hot.mp3"),
        ("cold", "lạnh", "lahn", "adj_cold.mp3"),
        ("fast / quick", "nhanh", "nyan", "adj_fast.mp3"),
        ("slow", "chậm", "chum", "adj_slow.mp3"),
        ("easy", "dễ", "yeh", "adj_easy.mp3"),
        ("difficult", "khó", "khaw", "adj_difficult.mp3"),
        ("clean", "sạch", "sahk", "adj_clean.mp3"),
        ("dirty", "bẩn", "bun", "adj_dirty.mp3"),
        ("interesting", "thú vị", "thoo vee", "adj_interesting.mp3"),
        ("boring", "chán", "chan", "adj_boring.mp3"),
        ("soft / smooth", "mịn / mềm", "min / mem", "adj_soft.mp3"),
        ("rough / hard", "thô / cứng", "thoh / kyung", "adj_rough.mp3"),
        ("shiny / glossy", "bóng", "bawng", "adj_shiny.mp3"),
        ("what color is it?", "Màu gì?", "mow yee", "desc_what_color.mp3"),
        ("do you have another color?", "Có màu khác không?", "kaw mow khahk khome", "desc_another_color.mp3"),
        ("I like this color", "Tôi thích màu này", "toy tick mow nay", "desc_like_color.mp3"),
        ("which one is better?", "Cái nào đẹp hơn?", "kai now dep huhn", "desc_which_better.mp3"),
        ("is there a bigger one?", "Có cái lớn hơn không?", "kaw kai luhn huhn khome", "desc_bigger_one.mp3"),
    ],
    "Family & People": [
        ("mother", "mẹ / má", "meh / mah", "family_mother.mp3"),
        ("father", "bố / ba", "boh / bah", "family_father.mp3"),
        ("parents", "bố mẹ / ba má", "boh meh / bah mah", "family_parents.mp3"),
        ("older sister", "chị", "chee", "pron_chi.mp3"),
        ("older brother", "anh", "anh", "pron_anh.mp3"),
        ("younger sibling", "em", "em", "pron_em.mp3"),
        ("younger sister", "em gái", "em gai", "family_younger_sister.mp3"),
        ("younger brother", "em trai", "em trai", "family_younger_brother.mp3"),
        ("husband", "chồng", "chohng", "family_husband.mp3"),
        ("wife", "vợ", "vuh", "family_wife.mp3"),
        ("child / children", "con", "kawn", "family_child.mp3"),
        ("son", "con trai", "kawn chai", "family_son.mp3"),
        ("daughter", "con gái", "kawn gai", "family_daughter.mp3"),
        ("grandmother", "bà", "bah", "pron_ba.mp3"),
        ("grandfather", "ông", "ohng", "pron_ong.mp3"),
        ("aunt (father's sister)", "cô", "koh", "pron_co.mp3"),
        ("aunt (mother's sister)", "dì", "dee", "family_aunt_di.mp3"),
        ("uncle (father's brother)", "chú", "choo", "pron_chu.mp3"),
        ("uncle (mother's brother)", "cậu", "koh-oo", "family_uncle_cau.mp3"),
        ("niece / nephew", "cháu", "chow", "family_niece_nephew.mp3"),
        ("family", "gia đình", "yah ding", "family_family.mp3"),
        ("relatives", "họ hàng", "haw hahng", "family_relatives.mp3"),
        ("this is my mother", "Đây là mẹ tôi", "day lah meh toy", "family_this_is_mother.mp3"),
        ("this is my father", "Đây là bố tôi", "day lah boh toy", "family_this_is_father.mp3"),
        ("this is my husband", "Đây là chồng tôi", "day lah chohng toy", "family_this_is_husband.mp3"),
        ("this is my wife", "Đây là vợ tôi", "day lah vuh toy", "family_this_is_wife.mp3"),
        ("my family has 4 people", "Gia đình tôi có bốn người", "yah ding toy kaw bone nguh-ee", "family_four_people.mp3"),
        ("I'm an only child", "Tôi là con một", "toy lah kawn moht", "family_only_child.mp3"),
        ("I'm the oldest", "Tôi là con cả", "toy lah kawn kah", "family_oldest.mp3"),
        ("I'm the youngest", "Tôi là con út", "toy lah kawn oot", "family_youngest.mp3"),
        ("I'm the middle child", "Tôi là con giữa", "toy lah kawn yuh-ah", "family_middle_child.mp3"),
        ("boyfriend", "bạn trai", "bahn chai", "rel_boyfriend.mp3"),
        ("girlfriend", "bạn gái", "bahn gai", "rel_girlfriend.mp3"),
        ("are you married?", "Bạn có gia đình chưa?", "bahn kaw yah ding chuh-ah", "rel_are_you_married.mp3"),
        ("I'm married", "Tôi đã kết hôn rồi", "toy dah ket hohn roy", "rel_im_married.mp3"),
        ("I'm single", "Tôi còn độc thân", "toy kawn dawk thun", "rel_im_single.mp3"),
        ("I'm divorced", "Tôi đã ly hôn", "toy dah lee hohn", "rel_im_divorced.mp3"),
        ("do you have children?", "Bạn có con chưa?", "bahn kaw kawn chuh-ah", "rel_have_children.mp3"),
        ("I have one child", "Tôi có một đứa con", "toy kaw moht duh-ah kawn", "rel_one_child.mp3"),
        ("Lunar New Year", "Tết", "tet", "cel_tet.mp3"),
        ("happy new year!", "Chúc mừng năm mới!", "chook mung num muh-ee", "cel_happy_new_year.mp3"),
        ("happy birthday!", "Chúc mừng sinh nhật!", "chook mung sing nyut", "cel_happy_birthday.mp3"),
        ("congratulations!", "Chúc mừng!", "chook mung", "cel_congratulations.mp3"),
        ("wedding", "đám cưới", "dahm kyuh-ee", "cel_wedding.mp3"),
        ("birthday", "sinh nhật", "sing nyut", "cel_birthday.mp3"),
    ],
    "Weather & Seasons": [
        ("dry season", "Mùa khô", "moo-ah khoh", "weather_dry_season.mp3"),
        ("rainy season", "Mùa mưa", "moo-ah muh-ah", "weather_rainy_season.mp3"),
        ("January", "Tháng 1", "tung moht", "month_1.mp3"),
        ("February", "Tháng 2", "tung hai", "month_2.mp3"),
        ("March", "Tháng 3", "tung ba", "month_3.mp3"),
        ("April", "Tháng 4", "tung bốn", "month_4.mp3"),
        ("May", "Tháng 5", "tung năm", "month_5.mp3"),
        ("June", "Tháng 6", "tung sáu", "month_6.mp3"),
        ("July", "Tháng 7", "tung bảy", "month_7.mp3"),
        ("August", "Tháng 8", "tung tám", "month_8.mp3"),
        ("September", "Tháng 9", "tung chín", "month_9.mp3"),
        ("October", "Tháng 10", "tung mười", "month_10.mp3"),
        ("November", "Tháng 11", "tung mười một", "month_11.mp3"),
        ("December", "Tháng 12", "tung mười hai", "month_12.mp3"),
        ("weather (general)", "Thời tiết", "thoy tyet", "weather_general.mp3"),
        ("sky / weather", "Trời", "choy", "weather_sky.mp3"),
        ("season", "Mùa", "moo-ah", "weather_season.mp3"),
        ("rain / to rain", "Mưa", "muh-ah", "weather_rain.mp3"),
        ("sunshine / sunny", "Nắng", "nahng", "weather_sunny.mp3"),
        ("hot", "Nóng", "nawng", "adj_hot.mp3"),
        ("cold", "Lạnh", "lahng", "adj_cold.mp3"),
        ("cool / pleasant", "Mát", "maht", "weather_cool.mp3"),
        ("wind", "Gió", "yoh", "weather_wind.mp3"),
        ("cloud", "Mây", "may", "weather_cloud.mp3"),
        ("humid / damp", "Ẩm", "uhm", "weather_humid.mp3"),
        ("dry", "Khô", "khoh", "weather_dry.mp3"),
        ("storm / typhoon", "Bão", "bow", "weather_storm.mp3"),
        ("heavy rain", "Mưa to / Mưa lớn", "muh-ah taw / lun", "weather_heavy_rain.mp3"),
        ("flood", "Lũ lụt", "loo loot", "weather_flood.mp3"),
        ("lightning", "Sét", "set", "weather_lightning.mp3"),
        ("thunder", "Sấm", "sum", "weather_thunder.mp3"),
        ("fog / mist", "Sương mù", "suh-ung moo", "weather_fog.mp3"),
        ("monsoon wind", "Gió mùa", "yoh moo-ah", "weather_monsoon.mp3"),
        ("today's weather is nice", "Hôm nay trời đẹp", "home nay choy dep", "weather_nice_today.mp3"),
        ("it's very hot", "Nóng quá", "nawng kwah", "weather_so_hot.mp3"),
        ("it's raining", "Trời đang mưa", "choy dahng muh-ah", "weather_its_raining.mp3"),
        ("will it rain today?", "Hôm nay có mưa không?", "home nay kaw muh-ah khome", "weather_will_rain.mp3"),
    ],
    "Shopping & Market": [
        ("how much?", "Bao nhiêu tiền?", "bow nyew tyen", "shop_how_much.mp3"),
        ("too expensive!", "Đắt quá!", "dat kwah", "shop_too_expensive.mp3"),
        ("give me a better price", "Bớt giá đi", "buht yah dee", "shop_better_price.mp3"),
        ("I'll buy it", "Tôi mua", "toy moo-ah", "shop_ill_buy.mp3"),
        ("I'm just looking", "Tôi chỉ xem thôi", "toy chee sem thoy", "shop_just_looking.mp3"),
        ("I don't want it", "Tôi không muốn", "toy khome moo-uhn", "shop_dont_want.mp3"),
        ("do you have...?", "Bạn có... không?", "bahn kaw... khome", "shop_do_you_have.mp3"),
        ("cheaper please", "Rẻ hơn được không?", "reh huhn duh-uk khome", "shop_cheaper.mp3"),
        ("do you have change?", "Bạn có tiền lẻ không?", "bahn kaw tyen leh khome", "shop_change.mp3"),
        ("discount?", "Giảm giá được không?", "yahm yah duh-uk khome", "shop_discount.mp3"),
        ("price", "giá", "yah", "shop_price.mp3"),
        ("money", "tiền", "tyen", "shop_money.mp3"),
        ("5,000 dong", "năm nghìn đồng", "num ngin dome", "money_5k.mp3"),
        ("10,000 dong", "mười nghìn đồng", "muh-ee ngin dome", "money_10k.mp3"),
        ("20,000 dong", "hai mươi nghìn đồng", "hi muh-ee ngin dome", "money_20k.mp3"),
        ("50,000 dong", "năm mươi nghìn đồng", "num muh-ee ngin dome", "money_50k.mp3"),
        ("100,000 dong", "một trăm nghìn đồng", "moht chum ngin dome", "money_100k.mp3"),
        ("200,000 dong", "hai trăm nghìn đồng", "hi chum ngin dome", "money_200k.mp3"),
        ("500,000 dong", "năm trăm nghìn đồng", "num chum ngin dome", "money_500k.mp3"),
        ("1,000,000 dong", "một triệu đồng", "moht chyew dome", "money_1m.mp3"),
    ],
}

wb = openpyxl.Workbook()
wb.remove(wb.active)

header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
header_font = Font(bold=True, color="FFFFFF", size=11)
alt_fill = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")

for sheet_name, rows in tabs.items():
    ws = wb.create_sheet(title=sheet_name)
    headers = ["English", "Vietnamese", "Pronunciation (English)", "Audio File Name"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 22

    for row_idx, (eng, viet, pron, fname) in enumerate(rows, 2):
        ws.cell(row=row_idx, column=1, value=eng)
        ws.cell(row=row_idx, column=2, value=viet)
        ws.cell(row=row_idx, column=3, value=pron)
        ws.cell(row=row_idx, column=4, value=fname)
        if row_idx % 2 == 0:
            for col in range(1, 5):
                ws.cell(row=row_idx, column=col).fill = alt_fill

    ws.column_dimensions["A"].width = 40
    ws.column_dimensions["B"].width = 34
    ws.column_dimensions["C"].width = 30
    ws.column_dimensions["D"].width = 30

    ws.oddFooter.left.text = sheet_name
    ws.oddFooter.left.size = 10
    ws.oddFooter.right.text = "Page &P of &N"
    ws.oddFooter.right.size = 10

output_path = r"c:\Users\bobby\Documents\fluentsaigon\kim_recording_sheet.xlsx"
wb.save(output_path)

total = sum(len(v) for v in tabs.values())
print(f"Created: {output_path}")
print(f"Sheets: {len(tabs)}, Total rows: {total}")
for name, rows in tabs.items():
    print(f"  {name}: {len(rows)} entries")
